// <auto-generated/>

using System;

namespace DuckDb.Bindings
{
    /// <summary>
    /// No documentation.
    /// </summary>
    /// <unmanaged>DUCKDB_TYPE</unmanaged>
    /// <unmanaged-short>DUCKDB_TYPE</unmanaged-short>
    internal enum DuckdbType : Int32
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_INVALID</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_INVALID</unmanaged-short>
        Invalid = unchecked ((Int32)(0)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_BOOLEAN</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_BOOLEAN</unmanaged-short>
        Boolean = unchecked ((Int32)(1)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_TINYINT</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_TINYINT</unmanaged-short>
        Tinyint = unchecked ((Int32)(2)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_SMALLINT</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_SMALLINT</unmanaged-short>
        Smallint = unchecked ((Int32)(3)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_INTEGER</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_INTEGER</unmanaged-short>
        Integer = unchecked ((Int32)(4)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_BIGINT</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_BIGINT</unmanaged-short>
        Bigint = unchecked ((Int32)(5)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_FLOAT</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_FLOAT</unmanaged-short>
        Float = unchecked ((Int32)(6)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_DOUBLE</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_DOUBLE</unmanaged-short>
        Double = unchecked ((Int32)(7)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_TIMESTAMP</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_TIMESTAMP</unmanaged-short>
        Timestamp = unchecked ((Int32)(8)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_DATE</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_DATE</unmanaged-short>
        Date = unchecked ((Int32)(9)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_TIME</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_TIME</unmanaged-short>
        Time = unchecked ((Int32)(10)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_INTERVAL</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_INTERVAL</unmanaged-short>
        Interval = unchecked ((Int32)(11)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_HUGEINT</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_HUGEINT</unmanaged-short>
        Hugeint = unchecked ((Int32)(12)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>DUCKDB_TYPE_VARCHAR</unmanaged>
        /// <unmanaged-short>DUCKDB_TYPE_VARCHAR</unmanaged-short>
        Varchar = unchecked ((Int32)(13))}
}